
----代码表
DROP TABLE CNST_CODELIST_DATA;
CREATE TABLE CNST_CODELIST_DATA(
  CODEID VARCHAR(100) primary key,--主键
  CODETYPE VARCHAR(100) not null,--代码表类型
  CODEBS VARCHAR(100) not null,--标识
  CODENAME VARCHAR(100) not null,--名称
  CODEMEMO VARCHAR(1000)--备注
);
--创建视图
CREATE OR REPLACE VIEW CNSV_CODELIST AS
SELECT T1.*,T2.CODENAME AS CODETYPENAME FROM CNST_CODELIST_DATA T1
LEFT JOIN CNST_CODELIST_DATA T2 ON T1.CODETYPE=T2.CODEBS ORDER BY T1.Codememo ASC;

INSERT INTO CNST_CODELIST_DATA(CODEID,CODETYPE,CODEBS,CODENAME)
VALUES('0','UNKNOW','DMB','代码表');


--创建视图 风叶数据
CREATE OR REPLACE VIEW SHRY_FY_VIEW AS
SELECT T1.*,T3.ZSXM AS INPUTUSERNAME,T4.ZSXM AS UPDATEUSERNAME 
FROM SHRY_FY_DATA T1 
LEFT JOIN USERS T3 ON T1.INPUTUSER=T3.ID
LEFT JOIN USERS T4 ON T1.UPDATEUSER=T4.ID 
ORDER BY T1.UPDATEDATE DESC;

--创建视图 噪声数据
CREATE OR REPLACE VIEW SHRY_FY_ZS_VIEW AS
SELECT T1.*,T2.XH AS FYXH,T3.ZSXM AS INPUTUSERNAME,T4.ZSXM AS UPDATEUSERNAME 
FROM SHRY_FY_ZS_DATA T1
 LEFT JOIN SHRY_FY_DATA T2 ON T1.FYID=T2.FYID
LEFT JOIN USERS T3 ON T1.INPUTUSER=T3.ID
LEFT JOIN USERS T4 ON T1.UPDATEUSER=T4.ID 
ORDER BY T1.UPDATEDATE DESC;

--创建视图 总成数据
CREATE OR REPLACE VIEW SHRY_ZC_VIEW AS
SELECT T1.*,T2.XH AS FYXH,T5.XH AS DJXH,T2.DLHZJ AS DLHZJ,
T3.ZSXM AS INPUTUSERNAME,T4.ZSXM AS UPDATEUSERNAME 
FROM SHRY_ZC_DATA T1 
LEFT JOIN SHRY_FY_DATA T2 ON T1.FYID=T2.FYID
LEFT JOIN SHRY_DJ_DATA T5 ON T1.DJID=T5.DJID 
LEFT JOIN USERS T3 ON T1.INPUTUSER=T3.ID
LEFT JOIN USERS T4 ON T1.UPDATEUSER=T4.ID 
ORDER BY T1.UPDATEDATE DESC;

--创建视图 试验单数据
CREATE OR REPLACE VIEW SHRY_SYD_VIEW AS
SELECT T1.*,T2.XH AS SZCXH,T5.XH AS SFYXH,
T3.ZSXM AS INPUTUSERNAME,T4.ZSXM AS UPDATEUSERNAME 
FROM SHRY_SYD_DATA T1 
LEFT JOIN SHRY_ZC_DATA T2 ON T1.ZCID=T2.ZCID
LEFT JOIN SHRY_FY_DATA T5 ON T1.FYID=T5.FYID 
LEFT JOIN USERS T3 ON T1.INPUTUSER=T3.ID
LEFT JOIN USERS T4 ON T1.UPDATEUSER=T4.ID 
ORDER BY T1.UPDATEDATE DESC;

--创建视图 电机数据
CREATE OR REPLACE VIEW SHRY_DJ_VIEW AS
SELECT T1.*,T2.ZSXM AS INPUTUSERNAME,T3.ZSXM AS UPDATEUSERNAME
FROM SHRY_DJ_DATA  T1
LEFT JOIN USERS T2 ON T1.INPUTUSER=T2.ID
LEFT JOIN USERS T3 ON T1.UPDATEUSER=T3.ID
ORDER BY T1.UPDATEDATE DESC;


--创建视图 风叶性能数据
CREATE OR REPLACE VIEW SHRY_FYXN_VIEW AS
SELECT T1.*,T2.LXDH AS LXDH,T5.XH AS FYXH,
T3.ZSXM AS INPUTUSERNAME,T4.ZSXM AS UPDATEUSERNAME 
FROM SHRY_FYXN_DATA T1 
LEFT JOIN SHRY_SYD_DATA T2 ON T1.LXDID=T2.LXDID
LEFT JOIN SHRY_FY_DATA T5 ON T1.FYID=T5.FYID 
LEFT JOIN USERS T3 ON T1.INPUTUSER=T3.ID
LEFT JOIN USERS T4 ON T1.UPDATEUSER=T4.ID 
ORDER BY T1.UPDATEDATE DESC;


--创建视图 总成性能数据
CREATE OR REPLACE VIEW SHRY_ZCXN_VIEW AS
SELECT T1.*,T2.LXDH AS LXDH,T5.XH AS FYXH,T6.XH AS ZCXH,
T3.ZSXM AS INPUTUSERNAME,T4.ZSXM AS UPDATEUSERNAME 
FROM SHRY_ZCXN_DATA T1 
LEFT JOIN SHRY_SYD_DATA T2 ON T1.LXDID=T2.LXDID
LEFT JOIN SHRY_ZC_DATA T6 ON T1.ZCID=T6.ZCID 
LEFT JOIN SHRY_FY_DATA T5 ON T1.FYID=T5.FYID 
LEFT JOIN USERS T3 ON T1.INPUTUSER=T3.ID
LEFT JOIN USERS T4 ON T1.UPDATEUSER=T4.ID 
ORDER BY T1.UPDATEDATE DESC;

